### ISSUE TITLE
pdm torch lock fails with PDM 2.10.0

### ISSUE THREAD

**Issue by lucidfrontier45** [EmbarkStudios/pdm-plugin-torch#15]
It look like the internal API of PDM changed.

```py
Traceback (most recent call last):
  File "/home/du/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/data/home/du/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/core.py", line 295, in main
    return Core().main(args or sys.argv[1:])
  File "/data/home/du/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/core.py", line 208, in main
    raise cast(Exception, err).with_traceback(traceback) from None
  File "/data/home/du/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/core.py", line 203, in main
    self.handle(project, options)
  File "/data/home/du/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm/core.py", line 157, in handle
    command.handle(project, options)
  File "/data/home/du/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm_plugin_torch/main.py", line 405, in handle
    results[api] = do_lock(
  File "/data/home/du/.local/pipx/venvs/pdm/lib/python3.10/site-packages/pdm_plugin_torch/main.py", line 183, in do_lock
    data = format_lockfile(project, mapping, dependencies)
TypeError: format_lockfile() missing 2 required positional arguments: 'groups' and 'strategy'
```

pyproject.toml is as follows

```toml
[project]
name = ""
version = ""
description = ""
dependencies = []
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm.plugins.torch]

dependencies = [
   "torch==2.1.0"
]

lockfile = "torch.lock"
enable-cpu = true
enable-cuda = true
cuda-versions = ["cu121", "cu118"]
```

**Comment by tgolsson** [comment]
Thanks for the report! Seems like every version of PDM there's some form of breakage :(

**Comment by tgolsson** [comment]
Fixed in next release, hopefully made this afternoon! Thanks for the report.
